<?php
namespace api\controllers;

use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;
use common\models\Article;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    //重写数据集合的actionIndex这个方法,
    //重写前要把原有的Index动作方法unset掉
    public function actions()
    {
//        return parent::actions(); // TODO: Change the autogenerated stub
        $action = parent::actions();
        unset($action['index']);
        return $action;
    }

    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider(
            [
                'query' => $modelClass::find()->asArray(),
                'pagination' => ['pageSize' => 5],//设置页面有五条post
            ]);
    }

    public function actionSearch()
    {
        return Article::find()->where(['like','title',$_POST['keyword']])->all();
    }
    public function actionTest(){
        $contents = file_get_contents('php://input');
        $data = json_decode($contents,true);
        $user = Yii::$app->applet
            ->makeSession($data['code'])
            ->getUser($data['encryptedData'],$data['iv']);
        print_r($user);
    }
}