<?php
namespace api\controllers;

use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;
use common\models\Comment;

class CommentController extends ActiveController
{
    public $modelClass = 'common\models\Comment';


    public function actionGetusercomment()
    {
        $postID = \Yii::$app->request->post('post_id');

//        $post = \Yii::$app->db->createCommand("SELECT *,test_user.id AS user_id,post.id AS post_id,test_user.created_at AS user_create_time,post.created_at as create_time FROM post LEFT JOIN test_user ON post.appid = test_user.openid order by post.id desc limit 10")->queryAll();


        $result = \Yii::$app->db->createCommand("select * from test_comment LEFT JOIN test_user on test_comment.user_id = test_user.openid where post_id = $postID order by test_comment.created_at desc")->queryAll();
        return $result;
    }

    //重写数据集合的actionIndex这个方法,
    //重写前要把原有的Index动作方法unset掉
//    public function actions()
//    {
////        return parent::actions(); // TODO: Change the autogenerated stub
//        $action = parent::actions();
//        unset($action['index']);
//        return $action;
//    }
//
//    public function actionIndex()
//    {
//        $modelClass = $this->modelClass;
//        return new ActiveDataProvider(
//            [
//                'query' => $modelClass::find()->asArray(),
//                'pagination' => ['pageSize' => 5],//设置页面有五条post
//            ]);
//    }
//
//    public function actionSearch()
//    {
//        return Article::find()->where(['like','title',$_POST['keyword']])->all();
//    }
//    public function actionTest(){
//        $contents = file_get_contents('php://input');
//        $data = json_decode($contents,true);
//        $user = Yii::$app->applet
//            ->makeSession($data['code'])
//            ->getUser($data['encryptedData'],$data['iv']);
//        print_r($user);
//    }
}